export const INIT_USER = 'INIT_USER';
export const SET_ORGANIZATION = 'SET_ORGANIZATION';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const types = {
  INIT_USER,
  SET_ORGANIZATION,
  START_LOADING,
  STOP_LOADING,
};
